comparison.py

rust speed compare should use release profile

optimize rust build

---

Dockerfile
README.md
comparison.py
src/leibniz.ex

I tried to implement an example for Elixir similar to the other implementations. 
But due to problems with the current Dockerfile i didn't update the Results section or 
the speed-comparison plot. @niklas-heer

Add Elixir example

---

src/leibniz.jl

Putting the code in a function means that you get type stability dropping the time down to 145 ms on my computer.

fix Julia performance

---

comparison.py
src/leibniz.c
src/leibniz.cpp

I have simplified the code. Now both C and C++ implementations are about 28% faster than previous implementations. Everything is well commented as well.
On top of that, I have enabled compiler optimization for both C and C++ builds.

Updated C and C++ Programs

---

Earthfile
src/leibniz.rs

Some rust optimizations: should make the implementation and compilation similar to the C one

---

Earthfile

https://github.com/docker-library/julia/blob/2e5e820552348a4f9ef9a6044470a79e4b23610f/1.8/alpine3.16/Dockerfile

use a newer julia version

---

Earthfile
README.md
src/leibniz.f90

This is supposed to add Fortran 90 to the list :) if it is welcome
EDIT: done I think.

add fortran 90

---

Earthfile

LuaJIT should be very much faster than Lua

Add LuaJIT

---

Earthfile
src/leibniz.pl

Adds a Perl version as suggested in #3

✨ Add Perl version. Closes #3.

---

Earthfile

https://crystal-lang.org/reference/1.5/man/crystal/index.html

use release build for crystal

---

Earthfile
src/leibniz.swift

I'm not sure if this will work, but I thought the execution time was a bit odd.
I'm really bad at swift 😄

Make swift compile instead of just running

---

Earthfile
src/cs/Program.cs
src/cs/leibniz.csproj

✨ Add C# version.

---

Earthfile
src/leibniz.r

Again [credit](https://twitter.com/henrikbengtsson/status/1582180570540351488?s=20&t=KP9OYvoGjAxj4utpqnavSQ) to @HenrikBengtsson

Faster R startup

---

src/leibniz.f90

it still evaluates all the terms, one by one.
But it does so in a way that should lead to vector assembly code

faster fortran code

---

src/leibniz.py

This is just an port of the Julia simplification from #57 to Python.
I think it also improves the speed of the implementation a bit.
It is also closer to what you would normally do in Python if numpy is available.

simplify python implementation

---

Earthfile
src/leibniz.f90

Hi Niklas,
this is my final attempt to fix all the issues ridding this code:
- accuracy
- vectorization
In order to speedup my CI runs I did the bench on small scale
now it seems to be reliable, sorry for the trouble.

[fortran] fixes accuracy & vectorisation (maybe)

---

Earthfile
src/leibniz.lisp

This adds Common Lisp (SBCL) to the list.
This is just a port of C/C++ code.

Add Common Lisp (SBCL)

---

Earthfile
analyze.py

This adds the language version to the plot to better be able to keep track of it.
Also updates the Python version used to do the analysis.

✨ Add version to plot

---

scmeta/src/scmeta.cr

✨ Switch to numerical distance accuracy

---

src/leibniz.rs

I have unraveled the loop and eliminated a variable so that the compiler could vectorize the loop better, this resulted in a roughly 35% speed increase

Added support for vectoriation in rust

---

Earthfile
README.md

Vectorization is only available on nightly rust, as far as i can tell

Updated Earthfile to use latest nightly rust

---

Earthfile
src/leibniz.js

This adds a JavaScript version with https://bun.sh/

✨ Add bun for running Javascript

---

Earthfile

Now it is almost as fast as C version

Add some flags for GDC realization

---

Earthfile
src/leibniz.nim

Clean up Nim code.
Add GCC optimization flags that are used to compile leibniz.c.

Clean up Nim code and update compiler flags

---

src/leibniz.py

Remove unused import.

---

Earthfile
src/leibniz.adb

Add Ada implementation.
